// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB49f_U_xJrk2RDy4kzYRE0rnA6huMisaQ',
    appId: '1:1058830435931:web:df73a82402ce6736f6217e',
    messagingSenderId: '1058830435931',
    projectId: 'praktikum-mobile-79870',
    authDomain: 'praktikum-mobile-79870.firebaseapp.com',
    storageBucket: 'praktikum-mobile-79870.appspot.com',
    measurementId: 'G-J4VYV122RQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWC-hLx4MEXd8UncPe7akbqeAHdG8ReXY',
    appId: '1:1058830435931:android:bb66f972c35eb63cf6217e',
    messagingSenderId: '1058830435931',
    projectId: 'praktikum-mobile-79870',
    storageBucket: 'praktikum-mobile-79870.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhXxWDS6Xzy6RcaaJo5KjTxztWTV29dVY',
    appId: '1:1058830435931:ios:f888257bb9f7af52f6217e',
    messagingSenderId: '1058830435931',
    projectId: 'praktikum-mobile-79870',
    storageBucket: 'praktikum-mobile-79870.appspot.com',
    iosBundleId: 'com.example.praktikumMod1',
  );
}
